# Generated by Django 4.2.7 on 2023-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='time',
            field=models.CharField(choices=[('3-6', '3-6'), ('6-9', '6-9'), ('9-12', '9-12')], default=('3-6', '3-6'), max_length=20),
        ),
    ]
