# Generated by Django 4.2.7 on 2023-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_pdf_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
    ]
