# Generated by Django 4.2.7 on 2023-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pdf_crud', '0002_remove_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dec',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel assumenda ad nemo laudantium. Rem modi vitae adipisci magnam mollitia quos, maiores sit facere tempore dignissimos hic eaque, nesciunt voluptatibus. Facere.', max_length=250),
        ),
    ]
