# Generated by Django 4.2.7 on 2023-11-20 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_pdf_crud', '0004_alter_game_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_created=django.utils.timezone.now, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
