# Generated by Django 4.2.7 on 2023-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pdf_crud', '0006_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='update',
            field=models.IntegerField(default=0),
        ),
    ]
